name: Build Spring Boot Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Boot JAR
        run: ./gradlew clean bootJar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-application
          path: build/libs/*.jar
