name: Manual Release with Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release Name'
        required: true
      release_body:
        description: 'Release Description (Use \\n for new lines)'
        required: false
        default: 'Detailed description here\\nFurther details follow here'

permissions:
  contents: write  # This allows the workflow to push code to your repository

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the master branch
        uses: actions/checkout@v4
        with:
          ref: 'main'  # Specify the base branch

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Create Tag
        run: git tag ${{ github.event.inputs.tag_name }} -m "${{ github.event.inputs.release_name }}"

      - name: Push Tag to Repository
        run: git push origin ${{ github.event.inputs.tag_name }}

      - name: Process Release Description
        id: process_description
        run: echo "::set-output name=body::$(echo '${{ github.event.inputs.release_body }}' | sed 's/\\n/\n/g')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false

      - name: Replace newlines in release description
        run: |
          BODY="${{ github.event.inputs.release_body }}"
          BODY="${BODY//'\\n'/$'\n'}"
          echo "Processed body: $BODY"
          echo "::set-output name=body::$BODY"
        id: format_body

      - name: Update Release Description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = await github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.create_release.outputs.id }},
              body: "${{ steps.format_body.outputs.body }}"
            });

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: List output of build directory
        run: ls -l ./build/libs/

      - name: Get JAR file path
        id: jar_path
        run: echo "::set-output name=jar_file::$(ls ./build/libs/*.jar)"

      - name: Upload JAR File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.jar_path.outputs.jar_file }}
          asset_name: 'app.jar'
          asset_content_type: application/java-archive