name: Manual Release and Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release Name'
        required: true
      release_body:
        description: 'Release Description'
        required: false
        default: 'Release details'

permissions:
  contents: write  # This allows the workflow to push code to your repository

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the master branch
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Create Tag
        run: git tag ${{ github.event.inputs.tag_name }} -m "${{ github.event.inputs.release_name }}"

      - name: Push Tag to Repository
        run: git push origin ${{ github.event.inputs.tag_name }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false